version: '3.1'
services:
  web:
    image: registry.heroku.com/bgpg/web
    ports:
      - 4000:4000
    environment:
      TYPEORM_CONNECTION: mongodb
      TYPEORM_HOST: mongo
      TYPEORM_DATABASE: bgpg
      TYPEORM_PORT: 27017
      TYPEORM_SYNCHRONIZE: 1
      TYPEORM_ENTITIES: dist/entities/**/*.entity.js
      PORT: 4000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: bgpg
    volumes:
      - database:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
volumes:
  database: ~
